# Edit this file to add dependencies to environment,
# Then run `./lock-environment.sh` to generate reproducible lock files

# !!! If you are developing the website locally use the existing lock files
# for your platform (`conda create --name hackweek --file conda-osx-64.lock`)
name: geosmart
channels:
  - conda-forge
dependencies:
  - python=3.10
  - sphinxcontrib-bibtex
  - jupyter-book=0.13
  - jupytext
platforms:
  - linux-64
  - osx-64
